spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 15e480430baf53
    password: 4cca59adb66747
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: StrongPassword123
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: ${spring.application.name}-pool
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    defer-datasource-initialization: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  main:
    allow-circular-references: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  info:
    env:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

