spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 15e480430baf53
    password: 4cca59adb66747
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  main:
    allow-circular-references: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  info:
    env:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

